// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ZqYF3yo9Tio3CVSzKZA3m8iO2Ia64R8',
    appId: '1:222377879683:web:c95a229297fee7000413b6',
    messagingSenderId: '222377879683',
    projectId: 'notification-6611b',
    authDomain: 'notification-6611b.firebaseapp.com',
    storageBucket: 'notification-6611b.appspot.com',
    measurementId: 'G-DEBRRMSXX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1TDZ2Dd8VD6lYDtBvXw23yQ1_YpYkGKA',
    appId: '1:222377879683:android:389ec9e63e732a4b0413b6',
    messagingSenderId: '222377879683',
    projectId: 'notification-6611b',
    storageBucket: 'notification-6611b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZDP814Zqtn_0rOCtQqsUuvXW3TsiYQjM',
    appId: '1:222377879683:ios:8f98d7568f681aa60413b6',
    messagingSenderId: '222377879683',
    projectId: 'notification-6611b',
    storageBucket: 'notification-6611b.appspot.com',
    iosClientId: '222377879683-os6morilgqo953kcssonu2mcsoueb2u9.apps.googleusercontent.com',
    iosBundleId: 'com.notification.org.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZDP814Zqtn_0rOCtQqsUuvXW3TsiYQjM',
    appId: '1:222377879683:ios:8f98d7568f681aa60413b6',
    messagingSenderId: '222377879683',
    projectId: 'notification-6611b',
    storageBucket: 'notification-6611b.appspot.com',
    iosClientId: '222377879683-os6morilgqo953kcssonu2mcsoueb2u9.apps.googleusercontent.com',
    iosBundleId: 'com.notification.org.notification',
  );
}
